/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurCard: typeof import('./../.vitepress/theme/components/global/BlurCard.vue')['default']
    ChangelogsBlock: typeof import('./../.vitepress/theme/components/global/ChangelogsBlock.vue')['default']
    FunctionBlock: typeof import('./../.vitepress/theme/components/global/FunctionBlock.vue')['default']
  }
}
