name: check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build packages
        run: |
          pnpm --filter=@ephemeras/fs build
          pnpm --filter=@ephemeras/parser build

      - name: Check types
        run: pnpm types

      - name: Check unit test
        run: pnpm test
