name: deploy

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # https://github.com/pnpm/action-setup
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # https://pnpm.io/zh/cli/install#--frozen-lockfile
      - name: Install dependencies
        run: pnpm install

      - name: Build with VitePress
        run: |
          pnpm docs:build
          touch docs/.vitepress/dist/.nojekyll

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          publish_dir: docs/.vitepress/dist
