env:
  DISABLE_CACHE: true

name: gh-pages

on:
  push:
    branches:
      - main1
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout Repo
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # https://github.com/pnpm/action-setup
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      # https://pnpm.io/zh/cli/install#--frozen-lockfile
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: |
          pnpm --filter=@ephemeras/fs build
          pnpm --filter=@ephemeras/utils build
          pnpm --filter=@ephemeras/file build
          pnpm --filter=@ephemeras/profile build
          pnpm --filter=@ephemeras/compiler build
          pnpm --filter=@ephemeras/linter build

      - name: Build vitepress site
        env:
          PLATFORM: GitHub
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
