name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # https://github.com/pnpm/action-setup
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # https://pnpm.io/zh/cli/install#--frozen-lockfile
      - name: Install dependencies
        run: |
          pnpm install
          pnpm test
          pnpm test:coverage

      # Push each package
      # https://github.com/codecov/codecov-action
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: compiler
          files: ./packages/compiler/coverage/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: file
          files: ./packages/file/coverage/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: fs
          files: ./packages/fs/coverage/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: linter
          files: ./packages/linter/coverage/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: profile
          files: ./packages/profile/coverage/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: utils
          files: ./packages/utils/coverage/coverage-final.json
