name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # https://github.com/pnpm/action-setup
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      # https://pnpm.io/zh/cli/install#--frozen-lockfile
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: |
          pnpm --filter=@ephemeras/fs build
          pnpm --filter=@ephemeras/utils build
          pnpm --filter=@ephemeras/file build
          pnpm --filter=@ephemeras/profile build
          pnpm --filter=@ephemeras/compiler build
          pnpm --filter=@ephemeras/linter build

      - name: Build coverage
        run: |
          pnpm test
          pnpm test:coverage

      # Push each package
      # https://github.com/codecov/codecov-action
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          directory: ./packages/compiler/coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: compiler
          file: ./coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          directory: ./packages/file/coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: file
          file: ./coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          directory: ./packages/fs/coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: fs
          file: ./coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          directory: ./packages/linter/coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: linter
          file: ./coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          directory: ./packages/profile/coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: profile
          file: ./coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          directory: ./packages/utils/coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: utils
          file: ./coverage-final.json
